# Generated by Django 2.1.7 on 2019-02-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190225_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='seats',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
