# Generated by Django 2.1.7 on 2019-02-26 08:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_attend_seats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attend',
            new_name='Booking',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='seats',
            new_name='tickets',
        ),
    ]
