# Generated by Django 2.1.7 on 2019-02-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190226_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ending_time',
        ),
    ]
