# Generated by Django 2.1.7 on 2019-02-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190226_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
    ]
